#!/usr/bin/env python3
"""Inject a release `signingConfig` into Flutter's generated Android Gradle file.

The Flutter Android template signs release builds with the *debug* key by
default. This script rewrites `android/app/build.gradle.kts` so that release
builds are signed with an upload keystore described by `android/key.properties`
(storeFile / storePassword / keyAlias / keyPassword).

It is:
  * idempotent — running twice is a no-op;
  * guarded — if the expected anchors are missing (e.g. the template changed
    in a future Flutter version), it exits non-zero with a clear message instead
    of silently producing a debug-signed build.

Usage:
    python3 scripts/configure_android_signing.py [path/to/build.gradle.kts]
"""
from __future__ import annotations

import sys
from pathlib import Path

DEFAULT_PATH = "android/app/build.gradle.kts"

IMPORTS = (
    "import java.util.Properties\n"
    "import java.io.FileInputStream\n"
)

KEYSTORE_LOADER = """
// Added by scripts/configure_android_signing.py — load upload-key credentials.
val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    FileInputStream(keystorePropertiesFile).use { keystoreProperties.load(it) }
}
"""

SIGNING_CONFIGS = """
    signingConfigs {
        create("release") {
            val storeFilePath = keystoreProperties["storeFile"] as String?
            if (storeFilePath != null) {
                storeFile = file(storeFilePath)
                storePassword = keystoreProperties["storePassword"] as String?
                keyAlias = keystoreProperties["keyAlias"] as String?
                keyPassword = keystoreProperties["keyPassword"] as String?
            }
        }
    }
"""

MARKER = "signingConfigs {"  # idempotency sentinel
DEBUG_SIGNING = 'signingConfig = signingConfigs.getByName("debug")'
RELEASE_SIGNING = 'signingConfig = signingConfigs.getByName("release")'


def patch(text: str) -> str:
    if MARKER in text and 'create("release")' in text:
        print("Already patched — skipping.")
        return text

    # 1) Imports must sit at the very top of a .kts file.
    if "import java.util.Properties" not in text:
        text = IMPORTS + text

    # 2) Keystore loader just before the `android {` block.
    anchor = "\nandroid {"
    if anchor not in text:
        sys.exit(
            "ERROR: could not find `android {` block in the Gradle file — the "
            "Flutter template may have changed; update this script."
        )
    text = text.replace(anchor, KEYSTORE_LOADER + "\nandroid {", 1)

    # 3) signingConfigs block immediately inside `android {`.
    text = text.replace("\nandroid {", "\nandroid {\n" + SIGNING_CONFIGS, 1)

    # 4) Point the release build type at the release signing config.
    if DEBUG_SIGNING not in text:
        sys.exit(
            "ERROR: could not find the default release `signingConfig` line — "
            "the Flutter template may have changed; update this script."
        )
    text = text.replace(DEBUG_SIGNING, RELEASE_SIGNING, 1)
    return text


def main() -> None:
    path = Path(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_PATH)
    if not path.exists():
        sys.exit(
            f"ERROR: {path} not found. This script targets the Kotlin-DSL "
            "template (build.gradle.kts) generated by Flutter 3.29+."
        )
    original = path.read_text()
    patched = patch(original)
    if patched != original:
        path.write_text(patched)
        print(f"Patched {path} for release signing.")


if __name__ == "__main__":
    main()
